/**
 * GENERATED by tools/gen-overwatch-topology.cjs from inventory.json — do not edit.
 *
 * The deployed topology the overwatch page draws: every boundary, every unit
 * (including the ones that are permanently dark), and every declared link between
 * them. Regenerate after changing the inventory.
 */

export type BoundaryKind = "cloud" | "host" | "docker" | "logical";

export interface TopologyBoundary {
  id: string;
  label: string;
  kind: string;
  note?: string;
}

export interface TopologyUnit {
  id: string;
  label: string;
  kind: string;
  boundary: string;
  /** Rendered inside this unit's box — an engine inside the api process, say. */
  parent?: string;
  /** Pool members, listed rather than collapsed. */
  members?: string[];
  replicas?: number | string;
  concurrency?: number | string;
  version?: string;
  state?: string;
  unverified?: boolean;
  note?: string;
}

export interface TopologyEdge {
  from: string;
  to: string;
  kind: string;
  semantics?: string;
  async?: boolean;
  p50?: number;
  unverified?: boolean;
  label?: string;
}

export const BOUNDARIES: TopologyBoundary[] = [
  {
    "id": "edge",
    "label": "Public edge / ingress",
    "kind": "cloud",
    "note": "Cloudflare (orange) in front of the origin IP — no Cloudflare Tunnel is running on the host"
  },
  {
    "id": "coolify",
    "label": "Coolify control plane (host)",
    "kind": "host",
    "note": "coollabsio/coolify 4.3.23 + its own db/redis/realtime/sentinel"
  },
  {
    "id": "core",
    "label": "compose project vtm5vs1bjkltpx3atda799cv_phantix",
    "kind": "docker",
    "note": "Coolify-managed. 12 containers. One image tag for api + all 7 workers + beat + alert-daemon"
  },
  {
    "id": "queues",
    "label": "Redis broker / 10 celery queues",
    "kind": "logical",
    "note": "Queues are Redis lists inside the single redis container — logical, not separate processes"
  },
  {
    "id": "agi",
    "label": "compose project phantix-agi (phantix-agi_default)",
    "kind": "docker",
    "note": "Separate stack, systemd-attached to the Coolify networks. Own host network for the agent loop"
  },
  {
    "id": "sandbox",
    "label": "phantix-sandbox network",
    "kind": "docker",
    "note": "cap_drop ALL, NET_RAW only, pids 512, isolated network mode — tool containers live here, cut off from db/redis"
  },
  {
    "id": "mcp",
    "label": "MCP surface",
    "kind": "logical",
    "note": "NO MCP SERVER IS DEPLOYED. Only client adapters, both currently inert"
  },
  {
    "id": "hostsvc",
    "label": "Host-level systemd services (not containers)",
    "kind": "host",
    "note": "opencode, Burp Suite Pro + Xvfb/VNC, adb"
  },
  {
    "id": "strays",
    "label": "Unmanaged / stray containers",
    "kind": "docker",
    "note": "Not part of either compose project. Found running on the host"
  },
  {
    "id": "providers",
    "label": "Model endpoints (external)",
    "kind": "cloud",
    "note": "Keys verified SET/EMPTY on staging; reachability probed from the api container"
  },
  {
    "id": "egress",
    "label": "Egress / SaaS",
    "kind": "cloud",
    "note": "Outbound integrations actually called by engine code"
  },
  {
    "id": "targets",
    "label": "Targets & tenants",
    "kind": "cloud",
    "note": "What the scanners and agents are pointed at while running"
  }
];

export const UNITS: TopologyUnit[] = [
  {
    "id": "cloudflare",
    "label": "Cloudflare edge",
    "kind": "gateway",
    "boundary": "edge",
    "replicas": "global anycast",
    "note": "Server: cloudflare; CF-RAY seen from LHR/CDG. DYNAMIC, h3 advertised"
  },
  {
    "id": "traefik",
    "label": "coolify-proxy (Traefik v3.6)",
    "kind": "gateway",
    "boundary": "edge",
    "replicas": 1,
    "note": "Router Host(staging.phantix.site) -> api:8000, tls letsencrypt, gzip + redirect-to-https middleware"
  },
  {
    "id": "coolify",
    "label": "coolify 4.3.23",
    "kind": "supervisor",
    "boundary": "coolify",
    "replicas": 1,
    "note": "Deploys and watches the compose project; read-only API reachable with ~/.coolify_token"
  },
  {
    "id": "coolify-db",
    "label": "coolify-db (postgres:15)",
    "kind": "memory-store",
    "boundary": "coolify",
    "replicas": 1,
    "note": "Coolify's own metadata DB — not the product DB"
  },
  {
    "id": "coolify-redis",
    "label": "coolify-redis",
    "kind": "cache",
    "boundary": "coolify",
    "replicas": 1
  },
  {
    "id": "coolify-realtime",
    "label": "coolify-realtime 1.0.19",
    "kind": "observer",
    "boundary": "coolify",
    "replicas": 1
  },
  {
    "id": "coolify-sentinel",
    "label": "coolify-sentinel 1.0.1",
    "kind": "observer",
    "boundary": "coolify",
    "replicas": 1
  },
  {
    "id": "api",
    "label": "api (uvicorn)",
    "kind": "runner",
    "boundary": "core",
    "replicas": 1,
    "concurrency": 2,
    "note": "UVICORN_WORKERS=2. Hosts ALL 13 engines in-process plus the middleware chain, the engine bus and the engine registry. Holds /var/run/docker.sock."
  },
  {
    "id": "mw-ratelimit",
    "label": "slowapi rate limit",
    "kind": "supervisor",
    "boundary": "core",
    "parent": "api",
    "note": "RATE_LIMIT_ENABLED=true, RATE_LIMIT_DEFAULT=500/min, service key 120/min — Redis-backed, 429 + Retry-After"
  },
  {
    "id": "mw-timeout",
    "label": "RequestTimeout 10s",
    "kind": "supervisor",
    "boundary": "core",
    "parent": "api",
    "note": "API_REQUEST_TIMEOUT_SECONDS=10 — hard ceiling on any request-path work"
  },
  {
    "id": "mw-session",
    "label": "app-session + device token",
    "kind": "supervisor",
    "boundary": "core",
    "parent": "api",
    "note": "APP_SESSION_ENFORCE=true, 30 min absolute / 20 min inactivity, silent renewal"
  },
  {
    "id": "mw-dualcontrol",
    "label": "OrgOperate + dual control",
    "kind": "supervisor",
    "boundary": "core",
    "parent": "api",
    "note": "Blocks state-changing operations until an authorizer approves; Redis dual_control:{id}"
  },
  {
    "id": "mw-audit",
    "label": "audit + 5xx event middleware",
    "kind": "observer",
    "boundary": "core",
    "parent": "api",
    "note": "AUDIT_MIDDLEWARE_ASYNC=true; writes platform_events; injects X-Correlation-Id into every response"
  },
  {
    "id": "eng-control",
    "label": "control_plane",
    "kind": "engine",
    "boundary": "core",
    "parent": "api",
    "version": "0.1.0",
    "note": "411 endpoints — auth, orgs, billing, staff, support, integrations"
  },
  {
    "id": "eng-soc",
    "label": "soc_engine",
    "kind": "engine",
    "boundary": "core",
    "parent": "api",
    "version": "0.8.0",
    "note": "121 endpoints — detections, cases, rules, war-room, availability, endpoint monitoring"
  },
  {
    "id": "eng-asset",
    "label": "asset_engine",
    "kind": "engine",
    "boundary": "core",
    "parent": "api",
    "version": "0.3.0",
    "note": "70 endpoints — inventory, discovery, tags, GitHub/GitLab/Gitea, asset graph"
  },
  {
    "id": "eng-compliance",
    "label": "compliance_engine",
    "kind": "engine",
    "boundary": "core",
    "parent": "api",
    "version": "1.1.0",
    "note": "52 endpoints — NDPR/ISO/SOC2/PCI/GDPR mapping, questionnaires"
  },
  {
    "id": "eng-reporting",
    "label": "reporting_engine",
    "kind": "engine",
    "boundary": "core",
    "parent": "api",
    "version": "1.0.0",
    "note": "45 endpoints — report assembly, CVSS enrichment, finding tracker, funnel"
  },
  {
    "id": "eng-vapt",
    "label": "vapt_engine",
    "kind": "engine",
    "boundary": "core",
    "parent": "api",
    "version": "0.1.0",
    "note": "40 endpoints — campaigns, procedures, approvals, schedules, correlation"
  },
  {
    "id": "eng-ops",
    "label": "operations_engine",
    "kind": "engine",
    "boundary": "core",
    "parent": "api",
    "version": "0.2.0",
    "note": "34 endpoints — monitoring, /status, developer logs, superadmin terminal"
  },
  {
    "id": "eng-scanner",
    "label": "scanner_engine",
    "kind": "engine",
    "boundary": "core",
    "parent": "api",
    "version": "0.1.0",
    "note": "30 endpoints — scan orchestration, tool adapters, cloud security"
  },
  {
    "id": "eng-ai",
    "label": "ai_engine",
    "kind": "engine",
    "boundary": "core",
    "parent": "api",
    "version": "1.1.0",
    "note": "Chief Security Agent, verification, autofix, AGI service (owns the AGI session cap of 4)"
  },
  {
    "id": "eng-threat",
    "label": "threat_model_engine",
    "kind": "engine",
    "boundary": "core",
    "parent": "api",
    "version": "1.0.0",
    "note": "18 endpoints — /context, threat models, document + diagram ingestion"
  },
  {
    "id": "eng-risk",
    "label": "risk_engine",
    "kind": "engine",
    "boundary": "core",
    "parent": "api",
    "version": "0.1.0",
    "note": "14 endpoints — scoring, treatments, residual risk"
  },
  {
    "id": "eng-audit",
    "label": "audit_engine",
    "kind": "engine",
    "boundary": "core",
    "parent": "api",
    "version": "0.2.0",
    "note": "14 endpoints — immutable audit trail"
  },
  {
    "id": "eng-alert",
    "label": "alert_engine",
    "kind": "engine",
    "boundary": "core",
    "parent": "api",
    "version": "0.1.0",
    "note": "13 endpoints — severity-routed notifications"
  },
  {
    "id": "engine-bus",
    "label": "engine bus",
    "kind": "bus",
    "boundary": "core",
    "parent": "api",
    "note": "IN-PROCESS subscriber registry (not Redis pub/sub, not LISTEN/NOTIFY). ~90 event contracts. Non-local subscribers fan out through celery as one message per event."
  },
  {
    "id": "engine-registry",
    "label": "engine registry",
    "kind": "registry",
    "boundary": "core",
    "parent": "api",
    "note": "Manifest-driven: 13/13 registered, 0 missing. Builds the /status engine + endpoint inventory."
  },
  {
    "id": "superadmin-term",
    "label": "superadmin terminal (local PTY)",
    "kind": "supervisor",
    "boundary": "core",
    "parent": "api",
    "note": "SUPERADMIN_TERMINAL_ENABLED=true, MODE=local, shell /bin/bash — a shell inside the api container, reachable from the admin API"
  },
  {
    "id": "worker-scans",
    "label": "worker-scans",
    "kind": "runner",
    "boundary": "core",
    "replicas": 1,
    "concurrency": 3,
    "note": "celery -Q scans -c 3. Mounts docker.sock (foreground `docker run` for tool containers)."
  },
  {
    "id": "worker-vapt",
    "label": "worker-vapt",
    "kind": "runner",
    "boundary": "core",
    "replicas": 1,
    "concurrency": 2,
    "note": "celery -Q vapt -c 2. max_retries=0 on run_campaign by design."
  },
  {
    "id": "worker-ai",
    "label": "worker-ai",
    "kind": "runner",
    "boundary": "core",
    "replicas": 1,
    "concurrency": 1,
    "note": "celery -Q ai -c 1. Single slot for every LLM task."
  },
  {
    "id": "worker-alerts",
    "label": "worker-alerts",
    "kind": "runner",
    "boundary": "core",
    "replicas": 1,
    "concurrency": 2
  },
  {
    "id": "worker-reports",
    "label": "worker-reports",
    "kind": "runner",
    "boundary": "core",
    "replicas": 1,
    "concurrency": 1,
    "note": "--max-memory-per-child=500000"
  },
  {
    "id": "worker-bus",
    "label": "worker-bus",
    "kind": "runner",
    "boundary": "core",
    "replicas": 1,
    "concurrency": 2,
    "note": "Also drains the default `celery` queue: staff alerts, funnel, ops, soc, agi.semantica_ingest"
  },
  {
    "id": "worker-programme",
    "label": "worker-programme",
    "kind": "runner",
    "boundary": "core",
    "replicas": 1,
    "concurrency": 2
  },
  {
    "id": "beat",
    "label": "beat (RedBeat)",
    "kind": "supervisor",
    "boundary": "core",
    "replicas": 1,
    "note": "Single leader holding securegraph:redbeat:lock (TTL 47s at sample). 26 scheduled entries. No beat-standby in staging."
  },
  {
    "id": "alert-daemon",
    "label": "alert-daemon",
    "kind": "supervisor",
    "boundary": "core",
    "replicas": 1,
    "note": "Non-Celery asyncio loop, --interval 5, batch 50. Heartbeat fresh (age 2.2s at sample). The liveness path that does not go through Celery."
  },
  {
    "id": "job-reaper",
    "label": "job_reaper",
    "kind": "supervisor",
    "boundary": "core",
    "parent": "worker-bus",
    "note": "Every 300s: reaps stalled ai_agent_runs, repo jobs, reports, vapt campaigns, scan_jobs (-> interrupted + resumable, celery revoke SIGTERM), discovery_jobs"
  },
  {
    "id": "sandbox-image-oneshot",
    "label": "sandbox-image (one-shot)",
    "kind": "runner",
    "boundary": "core",
    "replicas": "run-once per deploy",
    "note": "docker:27-cli; builds phantix-agi-sandbox:latest and creates the keeper container. Last run Exited(0) 3 days ago."
  },
  {
    "id": "db",
    "label": "db (postgres:16-alpine)",
    "kind": "memory-store",
    "boundary": "core",
    "replicas": 1,
    "note": "Platform DB `phantix`. max_connections 150, shared_buffers 1GB, work_mem 8MB, mem_limit 3g. Pool per process 10 + 10 overflow."
  },
  {
    "id": "security-db",
    "label": "bench-security-db (postgres:16-alpine)",
    "kind": "memory-store",
    "boundary": "strays",
    "replicas": 1,
    "note": "DB `phantix_security`, schemas: public + phantix. Reached per-org through the SECURITY DB POOL (1 live pool, org 4, size 1 free 1, min 1 max 5, expire 90s). Credentials live encrypted in platform `customer_db_connections"
  },
  {
    "id": "redis",
    "label": "redis (redis:7-alpine)",
    "kind": "cache",
    "boundary": "core",
    "replicas": 1,
    "note": "One container, at least 9 distinct jobs: celery broker, celery result backend, redbeat, slowapi rate limit, per-org tool locks + global scan slots, security-db cred cache, leader election, scan result spool, agent author"
  },
  {
    "id": "object-store",
    "label": "phantix_storage volume",
    "kind": "object-store",
    "boundary": "core",
    "replicas": 1,
    "note": "OBJECT_STORAGE_BACKEND=local. Mounted /app/data. Buckets used by code: securegraph-apk-uploads, phantix-reports, securegraph-storage, securegraph-screenshots, securegraph-code-graphs. S3 endpoint/keys EMPTY."
  },
  {
    "id": "q-scans",
    "label": "scans",
    "kind": "queue",
    "boundary": "queues",
    "note": "Concurrency 3; also carries scan.orchestrate/run_work_item fan-out loop"
  },
  {
    "id": "q-vapt",
    "label": "vapt",
    "kind": "queue",
    "boundary": "queues",
    "note": "Concurrency 2; poll_schedules every 60s"
  },
  {
    "id": "q-ai",
    "label": "ai",
    "kind": "queue",
    "boundary": "queues",
    "note": "Concurrency 1 — the LLM choke point for the whole platform"
  },
  {
    "id": "q-alerts",
    "label": "alerts",
    "kind": "queue",
    "boundary": "queues",
    "note": "process_pending every 30s + staff alerts + billing lifecycle"
  },
  {
    "id": "q-reports",
    "label": "reports",
    "kind": "queue",
    "boundary": "queues"
  },
  {
    "id": "q-bus",
    "label": "bus",
    "kind": "queue",
    "boundary": "queues",
    "note": "Cross-process engine event fan-out + dead-letter retry (max 5, 60s)"
  },
  {
    "id": "q-celery",
    "label": "celery (default)",
    "kind": "queue",
    "boundary": "queues",
    "note": "Catch-all: ops, soc, staff_alerts, funnel, agi.semantica_ingest have no task_routes glob"
  },
  {
    "id": "q-autofix",
    "label": "autofix",
    "kind": "queue",
    "boundary": "queues"
  },
  {
    "id": "q-continuous",
    "label": "continuous",
    "kind": "queue",
    "boundary": "queues",
    "note": "continuous.reassess every 3600s, accepted_risk_review / context_drift_sweep / learning_feed daily"
  },
  {
    "id": "q-integrations",
    "label": "integrations",
    "kind": "queue",
    "boundary": "queues",
    "note": "health_checks 900s, refresh_tokens 3600s"
  },
  {
    "id": "agi-runner",
    "label": "phantix-agi-runner",
    "kind": "runner",
    "boundary": "agi",
    "replicas": 1,
    "concurrency": 4,
    "version": "0.4.0",
    "note": "FastAPI, single uvicorn worker, 0 sessions at sample. ALL session state in process memory — a restart loses every live session. Sessions capped at 4 by the API (PHANTIX_AGI_MAX_CONCURRENT_SESSIONS), not by the runner. Ho"
  },
  {
    "id": "agi-loop",
    "label": "_agent_loop (orchestrator)",
    "kind": "specialist-agent",
    "boundary": "agi",
    "parent": "agi-runner",
    "concurrency": "1 per session",
    "note": "Turn loop: rebuild prompt (system prompt + last 8 history entries), stream model, dispatch tools, evaluate stop. MAX_TURNS_PER_PHASE=40, MAX_AUTONOMOUS_TURNS=3000, MAX_TOOLS=8000. Can sit in clarification wait for 24h by"
  },
  {
    "id": "agi-oversight",
    "label": "oversight / mission control",
    "kind": "supervisor",
    "boundary": "agi",
    "parent": "agi-runner",
    "note": "VERDICTS allow|gate|require_confirmation|steer|deny + DriftMonitor (window 10, threshold 4). Wired at _oversight_gate, but NOTHING sets oversight_enforced=True anywhere in the repo → in this deployment it observes and do"
  },
  {
    "id": "agi-finding-mgr",
    "label": "finding_manager",
    "kind": "supervisor",
    "boundary": "agi",
    "parent": "agi-runner",
    "concurrency": 8,
    "note": "Concurrency 8, batch 32, poll 6s, max 500. Concurrently verifies and promotes findings for the life of the session."
  },
  {
    "id": "agi-verifier",
    "label": "candidate_verifier",
    "kind": "specialist-agent",
    "boundary": "agi",
    "parent": "agi-runner",
    "concurrency": 12,
    "note": "Skeptical triager, 3 turns / 45s deadline. Verify-all fan-out concurrency 12, budget 900s. Die -> inconclusive, never dropped."
  },
  {
    "id": "agi-exploit-verifier",
    "label": "exploit_subagent",
    "kind": "specialist-agent",
    "boundary": "agi",
    "parent": "agi-runner",
    "concurrency": 12,
    "note": "Adversarial exploit auditor, 4 turns / 60s"
  },
  {
    "id": "agi-recon",
    "label": "recon_subagent",
    "kind": "specialist-agent",
    "boundary": "agi",
    "parent": "agi-runner",
    "note": "Read-only recon, 5 turns / 90s. Tools http_get, dns_lookup, nmap_top."
  },
  {
    "id": "agi-autofix",
    "label": "autofix_subagent",
    "kind": "specialist-agent",
    "boundary": "agi",
    "parent": "agi-runner",
    "note": "Advisory remediation, sequential per finding, 45s deadline, loops up to 20 findings"
  },
  {
    "id": "agi-pi",
    "label": "pi_subagent",
    "kind": "specialist-agent",
    "boundary": "agi",
    "parent": "agi-runner",
    "concurrency": 2,
    "note": "Spawns the `pi` CLI headless as a subprocess. Provider zai, model glm-5.3-flash, tools read,grep,find,ls,bash, timeout 120s, max 2 concurrent."
  },
  {
    "id": "agi-sweepers",
    "label": "specialist sweepers (15)",
    "kind": "specialist-agent",
    "boundary": "agi",
    "parent": "agi-runner",
    "members": [
      "class_sweeper",
      "injection",
      "authz",
      "upload",
      "rce",
      "probe",
      "js",
      "supply_chain",
      "rate",
      "crypto",
      "integrity",
      "bopla",
      "bfla",
      "business_flow",
      "inventory"
    ],
    "concurrency": "sequential",
    "note": "One pool, sequential, max_assignments=1, 180s budget each. Triggered ONLY by the JOB_DONE coverage gate and only when autonomy=high (model_led_prompt). The idle path does NOT call them."
  },
  {
    "id": "agi-knowledge",
    "label": "knowledge_keeper",
    "kind": "specialist-agent",
    "boundary": "agi",
    "parent": "agi-runner",
    "note": "The only thing resembling retrieval: injects prior session summaries + a static 12-category gap playbook into the prompt. Writes agi_knowledge_summaries via the API. NOTE: there is no vector store, no embedding call and "
  },
  {
    "id": "agi-artifacts",
    "label": "/data/agi-artifacts",
    "kind": "object-store",
    "boundary": "agi",
    "replicas": 1,
    "note": "Filesystem volume, token_urlsafe(24) dirs, 168h retention, purge at boot + every 6h + on teardown. Not S3."
  },
  {
    "id": "agi-guards",
    "label": "scope_guard + prompt_guard",
    "kind": "supervisor",
    "boundary": "agi",
    "parent": "agi-runner",
    "note": "scope_guard FAILS CLOSED (empty allowlist -> block). prompt_guard enforces forbidden.md. Second scope check inside oversight is inactive (called without scope_ok)."
  },
  {
    "id": "agi-toolcatalog",
    "label": "tool catalogue (47 sandbox + 34 advanced + 16 probes)",
    "kind": "specialist-agent",
    "boundary": "agi",
    "parent": "agi-runner",
    "note": "Plain in-process Python functions. 47 named sandbox binaries, 34 advanced tool names, 16 probe classes. NOT an MCP server, NOT a tool microservice, no JSON-RPC."
  },
  {
    "id": "sandbox-pool",
    "label": "sandbox pool",
    "kind": "sandbox",
    "boundary": "agi",
    "replicas": "warm 2 / max 8",
    "note": "asyncio.Semaphore(max). Acquire timeout 900s -> 503 on provision. Pooled and scrubbed between leases, NOT container-per-call. Each container: --memory 1g --cpus 1, 512 pids, cap_drop ALL + NET_RAW, ro scope mount, label "
  },
  {
    "id": "sandbox-a",
    "label": "phantix-agi-0f78afd24ab0",
    "kind": "sandbox",
    "boundary": "sandbox",
    "replicas": 1,
    "note": "Live, up 10 hours, leased/idle"
  },
  {
    "id": "sandbox-b",
    "label": "phantix-agi-3e9be8219a34",
    "kind": "sandbox",
    "boundary": "sandbox",
    "replicas": 1,
    "note": "Live, up 10 hours, leased/idle"
  },
  {
    "id": "sandbox-keeper",
    "label": "phantix-agi-sandbox-keeper",
    "kind": "sandbox",
    "boundary": "sandbox",
    "replicas": 1,
    "note": "Created (stopped) on purpose: pins the image against `docker image prune -a`"
  },
  {
    "id": "mcp-none",
    "label": "NO MCP SERVER DEPLOYED",
    "kind": "mcp-server",
    "boundary": "mcp",
    "replicas": 0,
    "note": "Verified: no mcp service in any compose file, no systemd unit, no .mcp.json, ~/.claude.json mcpServers == {}. grep -l mcp over services/phantix-agi returns 0 files. The agent tool layer is in-process Python + docker exec"
  },
  {
    "id": "mcp-burp",
    "label": "BurpMCPAdapter",
    "kind": "mcp-client",
    "boundary": "mcp",
    "state": "inert",
    "note": "BURP_MCP_ENDPOINT and BURP_API_URL are both EMPTY on staging -> the adapter returns stubbed results. Burp Suite Pro IS running on the host, but nothing on the request path reaches it (PROXY_FAILOVER_ENABLED=false)."
  },
  {
    "id": "mcp-caido",
    "label": "CaidoMCPAdapter",
    "kind": "mcp-client",
    "boundary": "mcp",
    "state": "disabled",
    "note": "CAIDO_MCP_ENABLED=false and CAIDO_SUSPENDED=true. CAIDO_GRAPHQL_URL is EMPTY on the api container. stdio launch configured (caido-mcp-server) but never invoked."
  },
  {
    "id": "mcp-customer",
    "label": "customer MCP introspection",
    "kind": "mcp-client",
    "boundary": "mcp",
    "state": "on-demand",
    "note": "mcp_surface.py POSTs JSON-RPC tools/list to a CUSTOMER-supplied endpoint, SSRF-guarded, <=50 tools, reads name+description only. This is the only live MCP code path, and it points outbound at tenants, not inward."
  },
  {
    "id": "opencode",
    "label": "opencode serve",
    "kind": "runner",
    "boundary": "hostsvc",
    "replicas": 1,
    "note": "Host systemd unit phantix-opencode.service, WorkingDirectory /opt/phantix-opencode/workspace, OPENCODE_CONFIG config/opencode.json. The 'contractor' that the AGI skill_handoff routes work to."
  },
  {
    "id": "opencode-proxy",
    "label": "phantix-opencode-proxy (socat)",
    "kind": "gateway",
    "boundary": "hostsvc",
    "replicas": 1,
    "note": "alpine/socat: TCP-LISTEN:4096,fork,reuseaddr -> host.docker.internal:4096. On the Coolify network, so containers reach it as http://phantix-opencode-proxy:4096. Up 7 weeks."
  },
  {
    "id": "burp",
    "label": "Burp Suite Professional",
    "kind": "runner",
    "boundary": "hostsvc",
    "replicas": 1,
    "note": "Host systemd, Xvfb DISPLAY=:99, JAVA_HOME /opt/BurpSuitePro/jre. Headless but GUI-shaped. Not addressed by any live config."
  },
  {
    "id": "burp-vnc",
    "label": "x11vnc :5901 + noVNC :6080",
    "kind": "observer",
    "boundary": "hostsvc",
    "replicas": 1,
    "note": "Interactive view of the Burp desktop"
  },
  {
    "id": "adb",
    "label": "adb server :5037",
    "kind": "runner",
    "boundary": "hostsvc",
    "replicas": 1,
    "unverified": true,
    "note": "MOBILE_UI_ENABLED=true, MOBILE_APPIUM_URL=http://127.0.0.1:4723 — but no process is listening on 4723. UNVERIFIED whether the mobile path functions."
  },
  {
    "id": "whtbin",
    "label": "whtbin :18082",
    "kind": "observer",
    "boundary": "hostsvc",
    "replicas": 1,
    "unverified": true,
    "note": "UNIDENTIFIED. Listening on 127.0.0.1 only. Not referenced by any config we found."
  },
  {
    "id": "stray-cohen",
    "label": "amazing_cohen",
    "kind": "stray",
    "boundary": "strays",
    "replicas": 1,
    "note": "UNMANAGED, up 9 days. Runs a shell loop probing katana / dalfox / kr / dirsearch / nuclei availability and hitting example.com. Not in any compose file."
  },
  {
    "id": "stray-others",
    "label": "trusting_solomon, relaxed_banzai, phantix-api-src-sandbox-image-1",
    "kind": "stray",
    "boundary": "strays",
    "replicas": 3,
    "note": "Exited containers left on the host (6d, 7d, 3d). No labels tying them to a live stack."
  },
  {
    "id": "m-deepseek",
    "label": "DeepSeek api.deepseek.com",
    "kind": "model-endpoint",
    "boundary": "providers",
    "state": "primary",
    "note": "Key SET. Probed from the api container: HTTP 401 (reachable). Primary for the platform ai_engine AND the AGI runner's stream."
  },
  {
    "id": "m-zai",
    "label": "Z.AI api.z.ai/paas/v4",
    "kind": "model-endpoint",
    "boundary": "providers",
    "state": "fallback",
    "note": "Key SET. HTTP 301 (reachable). Two roles: AGI GLM fallback on 401/402/408/429/5xx, and the provider for pi_subagent."
  },
  {
    "id": "m-agentrouter",
    "label": "AgentRouter agentrouter.org",
    "kind": "model-endpoint",
    "boundary": "providers",
    "state": "configured",
    "note": "Key SET, HTTP 200. AI_ALLOW_AGENTROUTER_IN_PROD=false but ENVIRONMENT=staging. Real historical calls succeeded: 'AI audit agent=executive_summary model=agentrouter/claude-opus-4-8'."
  },
  {
    "id": "m-moonshot",
    "label": "Moonshot api.moonshot.cn",
    "kind": "model-endpoint",
    "boundary": "providers",
    "state": "configured",
    "note": "KIMI_API_KEY SET, HTTP 200. No live call sites observed in logs."
  },
  {
    "id": "m-nvidia",
    "label": "NVIDIA NIM integrate.api.nvidia.com",
    "kind": "model-endpoint",
    "boundary": "providers",
    "state": "configured",
    "note": "NVIDIA_API_KEY SET (70 chars), NVIDIA_BASE_URL SET. No live call sites observed."
  },
  {
    "id": "m-typesafe",
    "label": "TypeSafe System One api.typesafe.ai",
    "kind": "model-endpoint",
    "boundary": "providers",
    "state": "configured",
    "note": "TYPESAFE_API_KEY SET (107 chars) on BOTH api and AGI runner. POST /v1/systemone. Used as a fast typed gate for routing and finding verdicts (real finding / expected access control / inconclusive). Max 80 gates per sessio"
  },
  {
    "id": "m-darkcluster",
    "label": "unconfigured providers",
    "kind": "model-endpoint",
    "boundary": "providers",
    "members": [
      "openai (gpt-4o-mini)",
      "anthropic (claude-3-haiku)",
      "xai (grok-3-mini)",
      "qwen (qwen-plus)",
      "openrouter",
      "gemini",
      "mistral",
      "groq",
      "together",
      "fireworks",
      "cerebras",
      "perplexity",
      "azure_openai",
      "local AI_COMPAT",
      "ollama"
    ],
    "replicas": 10,
    "state": "disabled",
    "note": "All keys EMPTY or vars absent. The provider catalogue implements them; staging does not. Shown so multiplicity is not hidden."
  },
  {
    "id": "e-brevo",
    "label": "Brevo SMTP relay",
    "kind": "observer",
    "boundary": "egress",
    "note": "smtp-relay.brevo.com:587, from=noreply@phantix.site. Live: /status confirms configured. Alert engine email channel + staff alerts."
  },
  {
    "id": "e-github",
    "label": "GitHub App (phantix-security-solutions)",
    "kind": "observer",
    "boundary": "egress",
    "note": "GITHUB_APP_ID + private key SET, slug phantix-security-solutions. Asset engine + branch review + autofix PRs."
  },
  {
    "id": "e-paystack",
    "label": "Paystack api.paystack.co",
    "kind": "observer",
    "boundary": "egress",
    "note": "Key SET. Billing + HMAC webhook ingress."
  },
  {
    "id": "e-nvd",
    "label": "NVD CVE API",
    "kind": "observer",
    "boundary": "egress",
    "note": "NVD_API_KEY SET. reporting_engine cvss_enricher. Beat: refresh-cve-cache-weekly."
  },
  {
    "id": "e-vt",
    "label": "VirusTotal",
    "kind": "observer",
    "boundary": "egress",
    "note": "Key SET (64 chars). yaml_scan_executor IP reputation."
  },
  {
    "id": "e-ddg",
    "label": "DuckDuckGo HTML",
    "kind": "observer",
    "boundary": "egress",
    "note": "PHANTIX_AGI_WEB_SEARCH_PROVIDER=duckduckgo. The AGI research path. TAVILY_API_KEY is EMPTY."
  },
  {
    "id": "e-dead-channels",
    "label": "Telegram / WhatsApp / Tavily / Mailinator / OTX / urlscan / Mnemonic",
    "kind": "observer",
    "boundary": "egress",
    "state": "empty-keys",
    "note": "Channels exist in code and are advertised in the alert policy (critical -> email + WhatsApp + Telegram), but every token is EMPTY on staging. Critical alerts therefore degrade to email only. Flagged rather than dropped."
  },
  {
    "id": "e-es",
    "label": "Elasticsearch",
    "kind": "observer",
    "boundary": "egress",
    "state": "disabled",
    "note": "ELASTICSEARCH_ENABLED=false, no container running. /status reports it as ok+disabled."
  },
  {
    "id": "e-slack",
    "label": "Slack / Teams / Jira / Linear / PagerDuty / SARIF",
    "kind": "observer",
    "boundary": "egress",
    "state": "per-tenant",
    "note": "INTEGRATIONS_HUB_ENABLED=true. OAuth/webhook targets are per-org, so activity depends on tenant configuration, not on staging env."
  },
  {
    "id": "t-lab",
    "label": "phantixvulnserver.online (169.58.110.182)",
    "kind": "target",
    "boundary": "targets",
    "note": "Live target host: 22 and 443 both open from the origin. Where the AGI and VAPT runs are pointed. The second host 169.58.162.46 (phantix-vuln-lab) is unreachable."
  },
  {
    "id": "t-tenants",
    "label": "tenant orgs",
    "kind": "target",
    "boundary": "targets",
    "note": "Live org rows: 1 NexaPay, 3 QA Test Company, 4 Phantix Vulnerable Organization, 11 Phantix Funnel, 12 Bifoluwa. Org 4 is the one with an active security DB pool."
  },
  {
    "id": "t-embeddings",
    "label": "pgvector halfvec(384)",
    "kind": "vector-store",
    "boundary": "targets",
    "state": "inactive",
    "unverified": true,
    "note": "threat_model_engine embeddings + product_documents.embedding, HNSW. AI_EMBEDDING_ENABLED is not set (default false) and QDRANT_URL is absent. Present in schema, not running. This is why the map is not a RAG pipeline."
  }
];

export const EDGES: TopologyEdge[] = [
  {
    "from": "cloudflare",
    "to": "traefik",
    "kind": "http",
    "semantics": "proxy",
    "p50": 18,
    "label": "orange-cloud origin pull"
  },
  {
    "from": "traefik",
    "to": "api",
    "kind": "http",
    "semantics": "rpc",
    "p50": 2,
    "label": "Host() -> api:8000"
  },
  {
    "from": "api",
    "to": "mw-ratelimit",
    "kind": "inproc",
    "semantics": "rpc",
    "p50": 3,
    "label": "middleware chain"
  },
  {
    "from": "mw-ratelimit",
    "to": "mw-timeout",
    "kind": "inproc",
    "semantics": "rpc"
  },
  {
    "from": "mw-timeout",
    "to": "mw-dualcontrol",
    "kind": "inproc",
    "semantics": "gate"
  },
  {
    "from": "mw-dualcontrol",
    "to": "mw-session",
    "kind": "inproc",
    "semantics": "gate",
    "p50": 1
  },
  {
    "from": "mw-session",
    "to": "eng-control",
    "kind": "inproc",
    "semantics": "rpc",
    "p50": 4,
    "label": "routed to the owning engine"
  },
  {
    "from": "mw-ratelimit",
    "to": "redis",
    "kind": "redis",
    "semantics": "rpc",
    "p50": 1,
    "label": "limit counters"
  },
  {
    "from": "mw-dualcontrol",
    "to": "redis",
    "kind": "redis",
    "semantics": "rpc",
    "p50": 1,
    "label": "dual_control:{id}"
  },
  {
    "from": "mw-audit",
    "to": "db",
    "kind": "sql",
    "semantics": "append",
    "async": true,
    "p50": 12,
    "label": "platform_events, async"
  },
  {
    "from": "api",
    "to": "engine-bus",
    "kind": "inproc",
    "semantics": "fanout",
    "p50": 1,
    "label": "publish(event_type)"
  },
  {
    "from": "engine-bus",
    "to": "eng-risk",
    "kind": "inproc",
    "semantics": "fanout",
    "p50": 2,
    "label": "ScanCompleted -> risk"
  },
  {
    "from": "engine-bus",
    "to": "eng-alert",
    "kind": "inproc",
    "semantics": "fanout",
    "p50": 2,
    "label": "ScanCompleted / RiskCritical -> alert"
  },
  {
    "from": "engine-bus",
    "to": "eng-ai",
    "kind": "inproc",
    "semantics": "fanout",
    "p50": 2,
    "label": "FindingCreated -> ai"
  },
  {
    "from": "engine-bus",
    "to": "eng-asset",
    "kind": "inproc",
    "semantics": "fanout",
    "p50": 2
  },
  {
    "from": "engine-bus",
    "to": "eng-reporting",
    "kind": "inproc",
    "semantics": "fanout",
    "p50": 2,
    "label": "CampaignCompleted -> reporting"
  },
  {
    "from": "engine-bus",
    "to": "eng-soc",
    "kind": "inproc",
    "semantics": "fanout",
    "p50": 2
  },
  {
    "from": "engine-bus",
    "to": "eng-compliance",
    "kind": "inproc",
    "semantics": "fanout",
    "p50": 2
  },
  {
    "from": "engine-bus",
    "to": "eng-audit",
    "kind": "inproc",
    "semantics": "fanout",
    "p50": 2,
    "label": "AuditRecorded -> audit"
  },
  {
    "from": "engine-bus",
    "to": "q-bus",
    "kind": "celery",
    "semantics": "fanout",
    "async": true,
    "p50": 25,
    "label": "non-local subscriber -> one celery message"
  },
  {
    "from": "api",
    "to": "q-scans",
    "kind": "celery",
    "semantics": "compete",
    "async": true,
    "p50": 20,
    "label": "scan.orchestrate"
  },
  {
    "from": "api",
    "to": "q-vapt",
    "kind": "celery",
    "semantics": "compete",
    "async": true,
    "p50": 20,
    "label": "vapt.run_campaign"
  },
  {
    "from": "api",
    "to": "q-ai",
    "kind": "celery",
    "semantics": "compete",
    "async": true,
    "p50": 20,
    "label": "ai.process_request / agent.run"
  },
  {
    "from": "api",
    "to": "q-alerts",
    "kind": "celery",
    "semantics": "compete",
    "async": true,
    "p50": 20
  },
  {
    "from": "api",
    "to": "q-reports",
    "kind": "celery",
    "semantics": "compete",
    "async": true,
    "p50": 20
  },
  {
    "from": "api",
    "to": "q-celery",
    "kind": "celery",
    "semantics": "compete",
    "async": true,
    "p50": 20,
    "label": "agi.semantica_ingest, staff_alerts, funnel"
  },
  {
    "from": "api",
    "to": "q-autofix",
    "kind": "celery",
    "semantics": "compete",
    "async": true,
    "p50": 20
  },
  {
    "from": "api",
    "to": "q-continuous",
    "kind": "celery",
    "semantics": "compete",
    "async": true,
    "p50": 20
  },
  {
    "from": "api",
    "to": "q-integrations",
    "kind": "celery",
    "semantics": "compete",
    "async": true,
    "p50": 20
  },
  {
    "from": "q-scans",
    "to": "worker-scans",
    "kind": "celery",
    "semantics": "compete",
    "async": true,
    "p50": 30
  },
  {
    "from": "q-vapt",
    "to": "worker-vapt",
    "kind": "celery",
    "semantics": "compete",
    "async": true,
    "p50": 30
  },
  {
    "from": "q-ai",
    "to": "worker-ai",
    "kind": "celery",
    "semantics": "compete",
    "async": true,
    "p50": 30
  },
  {
    "from": "q-alerts",
    "to": "worker-alerts",
    "kind": "celery",
    "semantics": "compete",
    "async": true,
    "p50": 30
  },
  {
    "from": "q-reports",
    "to": "worker-reports",
    "kind": "celery",
    "semantics": "compete",
    "async": true,
    "p50": 30
  },
  {
    "from": "q-bus",
    "to": "worker-bus",
    "kind": "celery",
    "semantics": "compete",
    "async": true,
    "p50": 30
  },
  {
    "from": "q-celery",
    "to": "worker-bus",
    "kind": "celery",
    "semantics": "compete",
    "async": true,
    "p50": 30
  },
  {
    "from": "q-autofix",
    "to": "worker-programme",
    "kind": "celery",
    "semantics": "compete",
    "async": true,
    "p50": 30
  },
  {
    "from": "q-continuous",
    "to": "worker-programme",
    "kind": "celery",
    "semantics": "compete",
    "async": true,
    "p50": 30
  },
  {
    "from": "q-integrations",
    "to": "worker-programme",
    "kind": "celery",
    "semantics": "compete",
    "async": true,
    "p50": 30
  },
  {
    "from": "beat",
    "to": "redis",
    "kind": "redis",
    "semantics": "rpc",
    "p50": 2,
    "label": "redbeat lock + schedule"
  },
  {
    "from": "beat",
    "to": "q-alerts",
    "kind": "celery",
    "semantics": "compete",
    "async": true,
    "p50": 15,
    "label": "26 entries; 30s/60s/300s/daily"
  },
  {
    "from": "beat",
    "to": "q-vapt",
    "kind": "celery",
    "semantics": "compete",
    "async": true,
    "p50": 15,
    "label": "poll_schedules 60s"
  },
  {
    "from": "beat",
    "to": "q-celery",
    "kind": "celery",
    "semantics": "compete",
    "async": true,
    "p50": 15,
    "label": "reap_stalled_jobs 300s, expire pools 120s"
  },
  {
    "from": "beat",
    "to": "q-continuous",
    "kind": "celery",
    "semantics": "compete",
    "async": true,
    "p50": 15,
    "label": "reassess 3600s"
  },
  {
    "from": "beat",
    "to": "q-ai",
    "kind": "celery",
    "semantics": "compete",
    "async": true,
    "p50": 15,
    "label": "verify_findings_daily 17:30, remediation_sweep 18:15, kb_res"
  },
  {
    "from": "beat",
    "to": "q-scans",
    "kind": "celery",
    "semantics": "compete",
    "async": true,
    "p50": 15,
    "label": "flush_scan_result_spool 60s"
  },
  {
    "from": "beat",
    "to": "q-reports",
    "kind": "celery",
    "semantics": "compete",
    "async": true,
    "p50": 15
  },
  {
    "from": "beat",
    "to": "q-integrations",
    "kind": "celery",
    "semantics": "compete",
    "async": true,
    "p50": 15
  },
  {
    "from": "alert-daemon",
    "to": "db",
    "kind": "sql",
    "semantics": "poll",
    "p50": 14,
    "label": "process_pending_batch limit 50, every 5s"
  },
  {
    "from": "alert-daemon",
    "to": "redis",
    "kind": "redis",
    "semantics": "rpc",
    "p50": 2,
    "label": "heartbeat"
  },
  {
    "from": "worker-scans",
    "to": "db",
    "kind": "sql",
    "semantics": "rpc",
    "p50": 15
  },
  {
    "from": "worker-scans",
    "to": "security-db",
    "kind": "sql",
    "semantics": "compete",
    "p50": 22,
    "label": "per-org pool, max 5 conns, 30s statement timeout"
  },
  {
    "from": "worker-scans",
    "to": "sandbox-a",
    "kind": "exec",
    "semantics": "compete",
    "p50": 900,
    "label": "foreground docker run, host-binary fallback allowed"
  },
  {
    "from": "worker-scans",
    "to": "sandbox-b",
    "kind": "exec",
    "semantics": "compete",
    "p50": 900
  },
  {
    "from": "worker-scans",
    "to": "redis",
    "kind": "redis",
    "semantics": "gate",
    "p50": 3,
    "label": "tool_lock:org:{id} + global_scan_slots (GLOBAL_SCAN_CONCURRE"
  },
  {
    "from": "worker-scans",
    "to": "object-store",
    "kind": "file",
    "semantics": "append",
    "p50": 8
  },
  {
    "from": "worker-scans",
    "to": "q-bus",
    "kind": "celery",
    "semantics": "fanout",
    "async": true,
    "p50": 25,
    "label": "ScanCompleted / FindingCreated"
  },
  {
    "from": "worker-scans",
    "to": "e-github",
    "kind": "https",
    "semantics": "rpc",
    "p50": 420,
    "label": "branch review, repo clone + analyze"
  },
  {
    "from": "worker-vapt",
    "to": "worker-scans",
    "kind": "celery",
    "semantics": "rpc",
    "async": true,
    "p50": 60,
    "label": "scanner_adapter creates a scan for the step — vapt never run"
  },
  {
    "from": "worker-vapt",
    "to": "db",
    "kind": "sql",
    "semantics": "rpc",
    "p50": 15,
    "label": "vapt_campaigns / steps / approvals"
  },
  {
    "from": "worker-vapt",
    "to": "security-db",
    "kind": "sql",
    "semantics": "append",
    "p50": 22,
    "label": "vapt_correlated_findings"
  },
  {
    "from": "worker-vapt",
    "to": "mw-dualcontrol",
    "kind": "http",
    "semantics": "gate",
    "p50": 500,
    "label": "wait_for_approval step parks the campaign until a human appr"
  },
  {
    "from": "worker-vapt",
    "to": "opencode-proxy",
    "kind": "http",
    "semantics": "fallback",
    "p50": 300,
    "label": "PROXY_MCP_PROVIDER=auto, mitmproxy fallback=true, failover=f"
  },
  {
    "from": "worker-ai",
    "to": "m-deepseek",
    "kind": "https",
    "semantics": "fallback",
    "p50": 2400,
    "label": "deepseek-v4-flash, streaming, reasoning_effort=high"
  },
  {
    "from": "worker-ai",
    "to": "m-zai",
    "kind": "https",
    "semantics": "fallback",
    "p50": 2600,
    "label": "on 402/429/5xx"
  },
  {
    "from": "worker-ai",
    "to": "m-agentrouter",
    "kind": "https",
    "semantics": "fallback",
    "p50": 3200,
    "label": "claude-opus-4-8 — observed in real audit logs"
  },
  {
    "from": "worker-ai",
    "to": "m-typesafe",
    "kind": "https",
    "semantics": "gate",
    "p50": 600,
    "label": "typed routing + finding gates"
  },
  {
    "from": "worker-ai",
    "to": "db",
    "kind": "sql",
    "semantics": "rpc",
    "p50": 15,
    "label": "ai_audit_logs, ai_agent_runs, ai_usage_monthly"
  },
  {
    "from": "worker-ai",
    "to": "agi-runner",
    "kind": "http",
    "semantics": "rpc",
    "p50": 40,
    "label": "PHANTIX_AGI_SERVICE_URL=http://phantix-agi:8095, Bearer PHAN"
  },
  {
    "from": "worker-alerts",
    "to": "e-brevo",
    "kind": "smtp",
    "semantics": "broadcast",
    "p50": 1500
  },
  {
    "from": "worker-alerts",
    "to": "e-dead-channels",
    "kind": "https",
    "semantics": "broadcast",
    "p50": 900
  },
  {
    "from": "worker-alerts",
    "to": "db",
    "kind": "sql",
    "semantics": "append",
    "p50": 12,
    "label": "alert_events, alert_deliveries"
  },
  {
    "from": "worker-reports",
    "to": "object-store",
    "kind": "file",
    "semantics": "append",
    "p50": 900,
    "label": "phantix-reports bucket"
  },
  {
    "from": "worker-reports",
    "to": "e-nvd",
    "kind": "https",
    "semantics": "rpc",
    "p50": 800,
    "label": "refresh-cve-cache-weekly"
  },
  {
    "from": "worker-reports",
    "to": "q-ai",
    "kind": "celery",
    "semantics": "rpc",
    "async": true,
    "p50": 20,
    "label": "AIRequested -> narrative sections"
  },
  {
    "from": "worker-reports",
    "to": "db",
    "kind": "sql",
    "semantics": "rpc",
    "p50": 15
  },
  {
    "from": "worker-bus",
    "to": "db",
    "kind": "sql",
    "semantics": "fanout",
    "p50": 15,
    "label": "re-publishes to local subscribers"
  },
  {
    "from": "worker-programme",
    "to": "m-deepseek",
    "kind": "https",
    "semantics": "rpc",
    "p50": 2600,
    "label": "autofix generate + continuous_pr"
  },
  {
    "from": "worker-programme",
    "to": "e-github",
    "kind": "https",
    "semantics": "rpc",
    "p50": 700,
    "label": "signed autofix PRs (AUTOFIX_SIGNING_KEY)"
  },
  {
    "from": "worker-programme",
    "to": "security-db",
    "kind": "sql",
    "semantics": "append",
    "p50": 22
  },
  {
    "from": "job-reaper",
    "to": "db",
    "kind": "sql",
    "semantics": "rpc",
    "p50": 40,
    "label": "marks stalled rows, revokes celery tasks"
  },
  {
    "from": "job-reaper",
    "to": "security-db",
    "kind": "sql",
    "semantics": "rpc",
    "p50": 45,
    "label": "scan_jobs -> interrupted + resumable"
  },
  {
    "from": "api",
    "to": "agi-runner",
    "kind": "http",
    "semantics": "rpc",
    "async": true,
    "p50": 45,
    "label": "POST session provision — 429 agi_global_concurrency above 4,"
  },
  {
    "from": "agi-runner",
    "to": "agi-loop",
    "kind": "inproc",
    "semantics": "spawn",
    "async": true,
    "p50": 5,
    "label": "one asyncio task per session"
  },
  {
    "from": "agi-loop",
    "to": "m-deepseek",
    "kind": "https",
    "semantics": "stream",
    "p50": 2400,
    "label": "SSE stream, reasoning_content"
  },
  {
    "from": "agi-loop",
    "to": "m-zai",
    "kind": "https",
    "semantics": "fallback",
    "p50": 2600,
    "label": "GLM fallback on 401/402/403/408/429/500/502/503/504/520/524"
  },
  {
    "from": "agi-loop",
    "to": "sandbox-pool",
    "kind": "inproc",
    "semantics": "compete",
    "async": true,
    "p50": 1200,
    "label": "lease, semaphore(max 8), 900s queue timeout -> PoolTimeout -"
  },
  {
    "from": "sandbox-pool",
    "to": "sandbox-a",
    "kind": "exec",
    "semantics": "lease",
    "p50": 60
  },
  {
    "from": "sandbox-pool",
    "to": "sandbox-b",
    "kind": "exec",
    "semantics": "lease",
    "p50": 60
  },
  {
    "from": "sandbox-a",
    "to": "t-lab",
    "kind": "tcp",
    "semantics": "attempt",
    "p50": 300,
    "label": "tools hit the target; cap_drop ALL + NET_RAW; cannot reach d"
  },
  {
    "from": "sandbox-b",
    "to": "t-lab",
    "kind": "tcp",
    "semantics": "attempt",
    "p50": 300
  },
  {
    "from": "agi-loop",
    "to": "agi-toolcatalog",
    "kind": "inproc",
    "semantics": "rpc",
    "p50": 4
  },
  {
    "from": "agi-toolcatalog",
    "to": "agi-guards",
    "kind": "inproc",
    "semantics": "gate",
    "p50": 2,
    "label": "scope + forbidden check before every command"
  },
  {
    "from": "agi-loop",
    "to": "agi-sweepers",
    "kind": "inproc",
    "semantics": "compete",
    "p50": 60000,
    "label": "ONLY from the JOB_DONE coverage gate, only when autonomy=hig"
  },
  {
    "from": "agi-loop",
    "to": "agi-recon",
    "kind": "inproc",
    "semantics": "rpc",
    "p50": 90000
  },
  {
    "from": "agi-loop",
    "to": "agi-autofix",
    "kind": "inproc",
    "semantics": "rpc",
    "p50": 45000
  },
  {
    "from": "agi-loop",
    "to": "agi-pi",
    "kind": "subprocess",
    "semantics": "compete",
    "p50": 120000,
    "label": "pi CLI, max 2 concurrent, provider zai"
  },
  {
    "from": "agi-loop",
    "to": "opencode-proxy",
    "kind": "http",
    "semantics": "fallback",
    "p50": 300,
    "label": "skill_handoff -> install | opencode contract"
  },
  {
    "from": "opencode-proxy",
    "to": "opencode",
    "kind": "tcp",
    "semantics": "rpc",
    "p50": 5,
    "label": "socat -> host.docker.internal:4096"
  },
  {
    "from": "agi-finding-mgr",
    "to": "agi-verifier",
    "kind": "inproc",
    "semantics": "fanout",
    "async": true,
    "p50": 45000,
    "label": "concurrency 8, batch 32"
  },
  {
    "from": "agi-finding-mgr",
    "to": "agi-exploit-verifier",
    "kind": "inproc",
    "semantics": "fanout",
    "async": true,
    "p50": 60000
  },
  {
    "from": "agi-verifier",
    "to": "m-typesafe",
    "kind": "https",
    "semantics": "gate",
    "p50": 600,
    "label": "typed verdict: real finding | expected access control | inco"
  },
  {
    "from": "agi-finding-mgr",
    "to": "m-typesafe",
    "kind": "https",
    "semantics": "gate",
    "p50": 600,
    "label": "max 80 gates per session"
  },
  {
    "from": "agi-loop",
    "to": "agi-oversight",
    "kind": "inproc",
    "semantics": "gate",
    "p50": 800,
    "label": "ADVISORY ONLY in this deployment: nothing sets oversight_enf"
  },
  {
    "from": "agi-loop",
    "to": "agi-knowledge",
    "kind": "inproc",
    "semantics": "rpc",
    "async": true,
    "p50": 30,
    "label": "the 'R' in RAG here = prior session summaries + a static gap"
  },
  {
    "from": "agi-knowledge",
    "to": "api",
    "kind": "http",
    "semantics": "rpc",
    "async": true,
    "p50": 35,
    "label": "POST /api/v1/admin/agi/internal/sessions/{sid}/knowledge"
  },
  {
    "from": "agi-loop",
    "to": "api",
    "kind": "http",
    "semantics": "fanout",
    "async": true,
    "p50": 35,
    "label": "findings, activity, engine_call, transcripts — all callbacks"
  },
  {
    "from": "agi-loop",
    "to": "agi-artifacts",
    "kind": "file",
    "semantics": "append",
    "p50": 6
  },
  {
    "from": "agi-loop",
    "to": "e-ddg",
    "kind": "https",
    "semantics": "rpc",
    "p50": 900,
    "label": "SSRF-guarded web research; Tavily key is EMPTY"
  },
  {
    "from": "agi-loop",
    "to": "mcp-customer",
    "kind": "https",
    "semantics": "rpc",
    "p50": 400,
    "label": "agent_platform.mcp_surface tools/list against a tenant- supp"
  },
  {
    "from": "traefik",
    "to": "coolify",
    "kind": "http",
    "semantics": "rpc",
    "p50": 3,
    "label": "Coolify dashboard on :8000"
  },
  {
    "from": "coolify",
    "to": "coolify-db",
    "kind": "sql",
    "semantics": "rpc",
    "p50": 6
  },
  {
    "from": "coolify",
    "to": "coolify-redis",
    "kind": "redis",
    "semantics": "rpc",
    "p50": 2
  },
  {
    "from": "coolify",
    "to": "api",
    "kind": "docker",
    "semantics": "deploy",
    "async": true,
    "p50": 30000,
    "label": "compose up -d; recreates all 12 containers on deploy"
  },
  {
    "from": "api",
    "to": "object-store",
    "kind": "file",
    "semantics": "append",
    "p50": 8
  },
  {
    "from": "eng-threat",
    "to": "t-embeddings",
    "kind": "sql",
    "semantics": "rpc",
    "p50": 30,
    "unverified": true
  },
  {
    "from": "mcp-burp",
    "to": "burp",
    "kind": "http",
    "semantics": "rpc",
    "unverified": true
  },
  {
    "from": "mcp-caido",
    "to": "redis",
    "kind": "stdio",
    "semantics": "rpc",
    "async": true,
    "unverified": true
  },
  {
    "from": "worker-scans",
    "to": "mcp-customer",
    "kind": "https",
    "semantics": "rpc",
    "p50": 350,
    "unverified": true
  },
  {
    "from": "sandbox-image-oneshot",
    "to": "sandbox-keeper",
    "kind": "docker",
    "semantics": "rpc",
    "async": true,
    "p50": 60000,
    "label": "docker build + docker create keeper"
  },
  {
    "from": "cloudflare",
    "to": "t-tenants",
    "kind": "http",
    "semantics": "proxy",
    "p50": 20,
    "label": "platform.phantix.site / app.phantix.site / staff / attack / "
  },
  {
    "from": "e-ddg",
    "to": "t-tenants",
    "kind": "https",
    "semantics": "rpc",
    "p50": 400,
    "unverified": true
  },
  {
    "from": "api",
    "to": "eng-control",
    "kind": "inproc",
    "semantics": "rpc",
    "p50": 3,
    "label": "in-process route dispatch"
  },
  {
    "from": "api",
    "to": "eng-asset",
    "kind": "inproc",
    "semantics": "rpc",
    "p50": 3,
    "label": "in-process route dispatch"
  },
  {
    "from": "api",
    "to": "eng-scanner",
    "kind": "inproc",
    "semantics": "rpc",
    "p50": 3,
    "label": "in-process route dispatch"
  },
  {
    "from": "api",
    "to": "eng-vapt",
    "kind": "inproc",
    "semantics": "rpc",
    "p50": 3,
    "label": "in-process route dispatch"
  },
  {
    "from": "api",
    "to": "eng-risk",
    "kind": "inproc",
    "semantics": "rpc",
    "p50": 3,
    "label": "in-process route dispatch"
  },
  {
    "from": "api",
    "to": "eng-reporting",
    "kind": "inproc",
    "semantics": "rpc",
    "p50": 3,
    "label": "in-process route dispatch"
  },
  {
    "from": "api",
    "to": "eng-compliance",
    "kind": "inproc",
    "semantics": "rpc",
    "p50": 3,
    "label": "in-process route dispatch"
  },
  {
    "from": "api",
    "to": "eng-soc",
    "kind": "inproc",
    "semantics": "rpc",
    "p50": 3,
    "label": "in-process route dispatch"
  },
  {
    "from": "api",
    "to": "eng-threat",
    "kind": "inproc",
    "semantics": "rpc",
    "p50": 3,
    "label": "in-process route dispatch"
  },
  {
    "from": "api",
    "to": "eng-audit",
    "kind": "inproc",
    "semantics": "rpc",
    "p50": 3,
    "label": "in-process route dispatch"
  },
  {
    "from": "api",
    "to": "eng-alert",
    "kind": "inproc",
    "semantics": "rpc",
    "p50": 3,
    "label": "in-process route dispatch"
  },
  {
    "from": "api",
    "to": "eng-ops",
    "kind": "inproc",
    "semantics": "rpc",
    "p50": 3,
    "label": "in-process route dispatch"
  },
  {
    "from": "api",
    "to": "eng-ai",
    "kind": "inproc",
    "semantics": "rpc",
    "p50": 3,
    "label": "in-process route dispatch"
  },
  {
    "from": "eng-control",
    "to": "db",
    "kind": "sql",
    "semantics": "rpc",
    "p50": 14,
    "label": "platform tables"
  },
  {
    "from": "eng-asset",
    "to": "db",
    "kind": "sql",
    "semantics": "rpc",
    "p50": 14,
    "label": "platform tables"
  },
  {
    "from": "eng-vapt",
    "to": "db",
    "kind": "sql",
    "semantics": "rpc",
    "p50": 14,
    "label": "platform tables"
  },
  {
    "from": "eng-reporting",
    "to": "db",
    "kind": "sql",
    "semantics": "rpc",
    "p50": 14,
    "label": "platform tables"
  },
  {
    "from": "eng-compliance",
    "to": "db",
    "kind": "sql",
    "semantics": "rpc",
    "p50": 14,
    "label": "platform tables"
  },
  {
    "from": "eng-ai",
    "to": "db",
    "kind": "sql",
    "semantics": "rpc",
    "p50": 14,
    "label": "platform tables"
  },
  {
    "from": "eng-audit",
    "to": "db",
    "kind": "sql",
    "semantics": "rpc",
    "p50": 14,
    "label": "platform tables"
  },
  {
    "from": "eng-alert",
    "to": "db",
    "kind": "sql",
    "semantics": "rpc",
    "p50": 14,
    "label": "platform tables"
  },
  {
    "from": "eng-ops",
    "to": "db",
    "kind": "sql",
    "semantics": "rpc",
    "p50": 14,
    "label": "platform tables"
  },
  {
    "from": "eng-scanner",
    "to": "security-db",
    "kind": "sql",
    "semantics": "rpc",
    "p50": 20,
    "label": "per-org security schema"
  },
  {
    "from": "eng-risk",
    "to": "security-db",
    "kind": "sql",
    "semantics": "rpc",
    "p50": 20,
    "label": "per-org security schema"
  },
  {
    "from": "eng-soc",
    "to": "security-db",
    "kind": "sql",
    "semantics": "rpc",
    "p50": 20,
    "label": "per-org security schema"
  },
  {
    "from": "eng-threat",
    "to": "security-db",
    "kind": "sql",
    "semantics": "rpc",
    "p50": 20,
    "label": "per-org security schema"
  },
  {
    "from": "eng-ai",
    "to": "m-deepseek",
    "kind": "https",
    "semantics": "stream",
    "p50": 2400,
    "label": "POST /ai/agent/chat/stream"
  },
  {
    "from": "eng-ai",
    "to": "m-zai",
    "kind": "https",
    "semantics": "fallback",
    "p50": 2600,
    "label": "GLM fallback"
  },
  {
    "from": "eng-ai",
    "to": "m-typesafe",
    "kind": "https",
    "semantics": "gate",
    "p50": 600,
    "label": "typed gate"
  }
];

export const KIND_GROUP: Record<string, string> = {
  "runner": "runners",
  "engine": "engines",
  "supervisor": "supervisors",
  "specialist-agent": "agents",
  "mcp-server": "mcp",
  "mcp-client": "mcp",
  "model-endpoint": "models",
  "queue": "queues",
  "bus": "queues",
  "gateway": "gateways",
  "memory-store": "stores",
  "vector-store": "stores",
  "object-store": "stores",
  "cache": "stores",
  "observer": "observers",
  "sandbox": "sandboxes",
  "registry": "supervisors",
  "stray": "strays",
  "target": "targets"
};

export const KIND_COLOR: Record<string, string> = {
  "runner": "#4ade80",
  "engine": "#60a5fa",
  "supervisor": "#f0abfc",
  "specialist-agent": "#fbbf24",
  "mcp-server": "#f87171",
  "mcp-client": "#f87171",
  "model-endpoint": "#22d3ee",
  "queue": "#c084fc",
  "bus": "#c084fc",
  "gateway": "#94a3b8",
  "memory-store": "#34d399",
  "vector-store": "#2dd4bf",
  "object-store": "#38bdf8",
  "cache": "#34d399",
  "observer": "#a3a3a3",
  "sandbox": "#facc15",
  "registry": "#f0abfc",
  "stray": "#ef4444",
  "target": "#fb923c"
};

export const EDGE_COLOR: Record<string, string> = {
  "http": "#64748b",
  "https": "#22d3ee",
  "celery": "#c084fc",
  "redis": "#34d399",
  "sql": "#34d399",
  "inproc": "#4b5563",
  "exec": "#facc15",
  "subprocess": "#fbbf24",
  "file": "#38bdf8",
  "docker": "#94a3b8",
  "smtp": "#f0abfc",
  "tcp": "#fb923c",
  "stdio": "#f87171"
};
